### ISSUE TITLE
Please help me check new Reactome versions :)

### ISSUE THREAD

**Issue by DeniseSl22** [DeniseSl22/Reactome_converter4_tests#1]
Dear @mkutmon @egonw, please help me check new conversions of Reactome for the WP website.
I've made some small changes in the Reactome converter (so it recognized more IDs, since Reactome started to add Drug IDs which where not part of Anwesha's original code).
Since we cannot test these PWs on a test server website, I didn't upload them (yet) to WPs.
@egonw suggested to upload the GPMLs to github, and check the diffs. See https://github.com/DeniseSl22/Reactome_converter4_tests/commit/6cfb44720bff533e55bfc9f294f4cff978907ded .

This is a comparison of the first 85 PWs for version66, with the old converter, vs the first 85 PWs on the new converter.
@egonw: if it would be possible to compare both versions as RDF as well, that would be really cool!

I'll also upload version 67, created with the new converter (in a few minutes, takes some time).

**Comment by egonw** [comment]
First test results are available from https://github.com/DeniseSl22/Reactome_converter4_tests/tree/master/reports

**Comment by egonw** [comment]
To compare the `GPML` between versions, using the [new tags](https://github.com/DeniseSl22/Reactome_converter4_tests/tags), do:

```shell
git diff --follow v66_old v66_4 --  "B-WICH complex positively regulates rRNA expression.gpml"
```

Or:

```shell
git diff --follow v66_4 v67_4 --  "B-WICH complex positively regulates rRNA expression.gpml"
```

Mind you, after `v67_4` the filenames have been changed: spaces and brackets are replaced by `_`.

The output is complicated because internal graph ids have changed :/ For example:

```diff
-  <DataNode TextLabel="POLR1D " GraphId="e0033" Type="Protein" GroupRef="c3346">
+  <DataNode TextLabel="POLR1D " GraphId="a9b4a" Type="Protein" GroupRef="febac">
     <Attribute Key="cellular_location" Value="nucleoplasm" />
     <Attribute Key="complex_id" Value="R-HSA-73859" />
     <Attribute Key="copies_num" Value="1" />
     <Graphics CenterX="100.0" CenterY="750.0" Width="100.0" Height="20.0" ZOrder="32768" FontSize="10" Valign="Middle" />
     <Xref Database="Uniprot-TrEMBL" ID="Q9Y2S0" />
   </DataNode>
```

**Comment by egonw** [comment]
Okay, and here are the RDF changes, but also suffering from the graph id changes :(

```
git diff --follow branch/v66_old master -- wp
```
