### ISSUE TITLE
rename files with spaces replaced by an underscore (or removed)

### ISSUE THREAD

**Issue by egonw** [DeniseSl22/Reactome_converter4_tests#4]
Because it turns out that the GNU/Linux tools, particularly Makefiles, don't work well with spaces in file names :(

**Comment by egonw** [comment]
@DeniseSl22, I renamed the files in the repo, but I would suggest to update your script/code to replace spaces with underscores. Second, plz also replace `(` and `)` with nothing or underscores.

**Comment by DeniseSl22** [comment]
Yes, I'll check this ;). Thank you for the input!

**Comment by DeniseSl22** [comment]
Already part of converter code issues, see https://github.com/wikipathways/reactome2gpml-converter/issues/55 . I've adapted the readme of this repo with a workaround (for now).
